# Generated by Django 6.0.3 on 2026-03-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='certifications.certification')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_mappings', to='course.course')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
